databases:
  - name: posgrado-feca-db
    plan: free
    databaseName: feca
    user: feca_admin

services:
  - type: web
    name: posgrado-feca
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PGHOST
        fromDatabase:
          name: posgrado-feca-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: posgrado-feca-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: posgrado-feca-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: posgrado-feca-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: posgrado-feca-db
          property: password
      - key: PGSSLMODE
        value: require
